### ISSUE TITLE
Remove bibtex-completion dependency

### ISSUE THREAD

**Issue by bdarcus** [bdarcus/citar#246]
Not a high short term priority, but ...

#222 goes a long way towards this, but to finish would also need:

1. #245 
2. replace the at-point finder code, including ensuring that `embark-act` works correctly with it
3. rewrite the code that finds local bibs
4. maybe remove the "add-pdf" commands?
5. #308
6. check on whether there are any variable dependencies still

I think that's it?

**Comment by aikrahguzar** [comment]
I think we still use variables defined by `bibtex-completion` at places.

2,3 should be pretty simple. I will try my hand it but not likely any time soon.

**Comment by bdarcus** [comment]
No rush at all; I just wanted to write it down in one place.

**Comment by minad** [comment]
Since you only seem to use bibtex-completion in obsolete commands you could remove the dependency right away.

Inside the functions you could dynamically require bibtex-completion. Example:

https://github.com/bbatsov/projectile/blob/584ff420b2c5637b05be5c4808754d6e947ab6c1/projectile.el#L4068

Generally I consider this bad style - it is a bit overused in projectile. But in this case here, the dynamic require approach seems entirely justified.

**Comment by minad** [comment]
Since you obsoleted these commands - they should probably also be removed from the default keybindings.

https://github.com/bdarcus/citar/blob/e5cbae466ff913e33b5f00bc91d6224f5205786e/citar.el#L243-L244

**Comment by bdarcus** [comment]
Yeah, good point on the oversight.

I'm not sure I'm going to obsolete all of them, but did want to make people aware of it, and basically push them to advocate if they feel strongly.

Removing from the bindings does do that.
