### ISSUE TITLE
Add `:filter` arg to select-keys

### ISSUE THREAD

**Issue by bdarcus** [bdarcus/citar#272]
Maybe something like ...

```elisp
(seq-filter 
  (lambda (cand) 
    (string-match filter (car cand))) 
  candidates)
```

... so could do:

```elisp
(bibtex-actions-select-keys :filter "has:notes")
```

Performance may not be ideal with large collections, but flexibility would be high.

I don't think I would do this by default in this package, but it might be convenient to have.

**Comment by aikrahguzar** [comment]
I think this is a good idea, but two comments:

1)  We store the parsed entry along with the display string i.e a candidate is `(display-string key . entry)`. For the `has-field` kind of check, we should use the `entry` instead of string-match the display string. I think that should be faster than string match but should be checked. If needed we should be able to make performance better by changing the string keys to symbols. This would come at the cost of make the caching step take longer but I don't know what the impact would be.

2) I think we should go for maximum flexibility and the argument for `:filter` should be a function that acts on the `entry`.

**Comment by bdarcus** [comment]
> * We store the parsed entry along with the display string i.e a candidate is `(display-string key . entry)`. For the `has-field` kind of check, we should use the `entry` instead of `string-match` on the display string. 

But the entry doesn't necessarily have this particular info though.

**Comment by bdarcus** [comment]
When you have some time, @roshanshariff, can you take a look at this issue, especially https://github.com/bdarcus/citar/issues/272#issuecomment-913139375?

It's not critical by any means, but would be nice-to-have.

**Comment by roshanshariff** [comment]
Yeah, I was considering implementing this recently. I agree with @aikrahguzar that the predicate function should operate on keys and entries, not the formatted candidate string. And now, with the recent `citar-file` refactor, we have predicate functions for files and notes that would work perfectly here.

Does that seem like a reasonable design choice?

**Comment by bdarcus** [comment]
Yep.
