### ISSUE TITLE
remove s, s-format dependency

### ISSUE THREAD

**Issue by bdarcus** [bdarcus/citar#335]
In the interest of further removing dependencies, it would be nice to replace the current template formatting code, perhaps with `replace-regexp-in-string`.

Probably the best approach would just be to adapt the two relevant s functions; for example:

https://github.com/bdarcus/bibtex-actions/pull/336/commits/30ed7f61d067fc52aa721b56db11282a1a450829

**Comment by minad** [comment]
I was just about to mention this. There are a few unnecessary dependencies which should be avoided in my opinion: 

* s, f, ht - only wrappers around core functions. Nicer naming scheme than the core functions, but the packages are unidiomatic.
* dash - this one is more debatable. It allows to write functional/clojure like lisp style, which is unidiomatic in the wider elisp ecosystem. Then there are the more limited built-in seq and map libraries which can be used instead. However dash only focuses on lists, so it may have more performant implementations for some functions. But in these cases for lists only you can also fallback to plain old interative lisp (dolist etc) or the cl-lib.

**Comment by bdarcus** [comment]
That stuff is coming from the bibtex-completion dependency, and I thought I removed all of it and replaced with the seq and dolist stuff, except for s?

**Comment by minad** [comment]
It seems the main problem is s-format since there is no good built-in which provides the same functionality?

**Comment by bdarcus** [comment]
Correct.

**Comment by minad** [comment]
@bdarcus I stumbled over the `format-spec` library, which is part of Emacs. See https://www.gnu.org/software/emacs/manual/html_node/elisp/Custom-Format-Strings.html.

Maybe this is a viable alternative to `s.el`?

**Comment by minad** [comment]
Another option could be the formatting function from org-roam, see https://github.com/org-roam/org-roam/blob/c0c240b975c82a4e9b978a9e55f3af415aa91de6/org-roam-utils.el#L165-L195. They also recently dropped the f and s dependencies because of the nongnu elpa inclusion.

**Comment by bdarcus** [comment]
Yeah, I noticed that recent org-roam change, and was wondering. Thanks!

**Comment by localauthor** [comment]
I recently stumbled on format-spec too and did some playing around with it. It's fairly idiomatic, but pretty powerful. One shortcoming is that its templates are less transparent (ie, readable) than s-format templates.

Compare:
s-format: `"${author editor:30}     ${date year issued:4}     ${title:48}")`
format-spec: `"%->30a     %>4d     %>48t"`

As the above might indicated, format-spec also handles missing elements in a slightly less friendly way than s-format: rather than allowing you to include multiple fields in the template ("${author editor:30}" above, for example) and only resolving the first available, format-spec requires you to include the possible fields in what it calls the "specification."

In the format-spec template above, then, the "a" in the string "%->30a" stands for a value that is resolved elsewhere. so a list of possible values, like ("author" "editor"), would have to be in a function somewhere --- or, alternatively, in an alist.

The following seems to work:

```
(setq citar-templates
      '((main . "%->30a     %>4d     %>48t")
        (suffix . "          %>15k    %>12T   %K")
        (preview . "%>a (%d) %t, %p.\n")
        (note . "Notes on %a, %t")))

(defun citar--format-entry (entry width template)
  (format-spec template
               (list
                (cons ?a (citar-clean-string (citar-display-value '("author" "editor") entry)))
                (cons ?d (citar-clean-string (citar-display-value '("date" "year" "issued") entry)))
                (cons ?t (citar-clean-string (citar-display-value '("title") entry)))
                (cons ?k (citar-clean-string (citar-display-value '("=key=" "id") entry)))
                (cons ?T (citar-clean-string (citar-display-value '("=type=") entry)))
                (cons ?K (citar-clean-string (citar-display-value '("tags" "keywords") entry)))
                (cons ?p (citar-clean-string (citar-display-value '("journal" "journaltitle" "publisher" "container-title" "collection-title") entry))))
               t))

(defun citar--fields-to-parse ()
  (list "author" "editor" "date" "year" "issued" "title" "=key=" "=type" "tags" "keywords" "journal"
        "journaltitle" "publisher" "container-title" "collection-title"))
```

It could definitely be cleaned up, but a start in any case.

The `citar--fields-to-parse` would need to be changed, to somehow get the fields from the template (or elsewhere). The above function is just a bandaid, for test purposes.

Also, the "width" value in `citar--format-entry` isn't necessary, since format spec handles setting widths and truncating. Makes a lot of the current formatting functions unnecessary.

**Comment by bdarcus** [comment]
> Also, the "width" value in `citar--format-entry` isn't necessary, since format spec handles setting widths and truncating. Makes a lot of the current formatting functions unnecessary.

Cool. So not only would it remove a dependency, but would also simplify this code, and also add greater flexibility (since one can set alignment in the templates for different fields).

Seems the only downside is the slightly less transparent templates. But that seems a rather minor issue for this use case.

**Comment by roshanshariff** [comment]
There's one downside to doing truncation with `format-spec` instead of the current `citar--fit-to-width`: the extra text is completely deleted instead of being hidden using text properties. This means that if an entry has a long title (for example) which gets truncated, you won't be able to filter on any truncated text.

**Comment by bdarcus** [comment]
Oh yeah, I meant to test that, bit hadn't gotten around to it.

That's a problem actually.

**Comment by minad** [comment]
You don't have to make use of the truncation feature or do you?

**Comment by localauthor** [comment]
There's a format-spec PR here #540 that could do with some testing and adjustment, I'm sure.

As for the problem of truncation, you're certainly right, @roshanshariff, and that's not being dealt with in the present form at all.

It seems like that would generally be a problem specific to titles, right? And perhaps authors/editors.

Would it be unreasonable to include those fields in full in the "candidate-hidden" variable of `citar--format-candidates`? Maybe not an elegant solution, but the first one that comes to mind.
