### ISSUE TITLE
citar-latex auctex dependency

### ISSUE THREAD

**Issue by bdarcus** [bdarcus/citar#370]
Got a bug report where a user got an error installing via package-install because they didn't have auctex installed.

I thought that would only happen if loading a tex buffer.

It's why I was wondering earlier about a separate recipe for the latex adapter.

Thoughts @roshanshariff @minad?

**Comment by minad** [comment]
It seems there are only two calls to `reftex-*` functions. For now I would dynamically detect reftex at runtime and throw an error otherwise, similar to how you handled the obsolete bibtex-completion commands.

For now I would avoid splitting the package, since it is not yet clear if a split is justified. But I would still keep a potential split in mind for the long term. There is also the question what to do about biblio for bibtex fetching and citeproc. citeproc is required by org-cite, if I understood correctly? However since org-cite is part of org it also depends only dynamically on citeproc and throws an error if it is not available?

**Comment by minad** [comment]
Ah, there is also `TeX-parse-macro`, this is from auctex?

**Comment by bdarcus** [comment]
oc-csl has, for example, this at the top:

```elisp
(require 'citeproc nil t)
```

Should I do the equivalent?

**Comment by roshanshariff** [comment]
I always thought that AUCTeX and RefTeX were included in Emacs, but it seems like only the latter is. So if I'm not mistaken, there should be no problem with `(require reftex)`?

Then I looked at `reftex-auc.el` to see how they handle the auctex dependency. It looks like they've got `(declare-function FN "ext:tex" ARGS)` forms to make the byte compiler happy, and then they have a guard `(and (featurep 'tex-site) (featurep 'latex))` in the function `reftex-toggle-plug-into-AUCTeX`.

In particular, they don't make any attempt to `require` auctex. If the user is in a `LaTeX-mode` buffer they will have auctex loaded, and if they're not (because they don't have auctex installed or configured properly) then it's probably not a good idea to use `TeX-*` functions in it. So I think the two options are
1. Use a guard `(and (featurep 'tex-site) (featurep 'tex))`
2. Use `(fboundp TeX-{parse,current}-macro)`

Maybe the second option makes more sense for citar because of the more limited dependency on auctex?

**Comment by bdarcus** [comment]
Yeah, I was going to add oc-csl also uses the featurep approach.

https://github.com/andras-simonyi/oc-csl-ns/blob/06703c5a42f6aeb1fcf7c1552d8a6b4fc0bf9d28/oc-csl.el#L274

**Comment by bdarcus** [comment]
I pushed a little commit for this as part of #366.

https://github.com/bdarcus/citar/pull/366/commits/799bf688b191fb6904e3f211630258a6eb04779c
