### ISSUE TITLE
Custom completion categories and Embark keymaps

### ISSUE THREAD

**Issue by minad** [bdarcus/citar#381]
I've seen that citar defines its own completion categories `bib-reference`, `citation-key` and `oc-citation`. First I'd like to make the proposal to prefix the categories with `citar-` since they are Citar-specific as far as I understood. What is the difference between these categories? It seems you distinguish the categories mostly to provide different keymaps in Embark? This brings me to my second point - does it make sense to keep this distinction, since it goes a bit against the Embark spirit where no difference is made for the keymaps of objects coming from minibuffer or normal buffers. Of course it does not make sense to execute all actions on minibuffer candidates or buffer candidates. However Embark also allows to execute arbitrary actions via M-x on the current candidate, which makes this point less relevant.

**Comment by bdarcus** [comment]
> What is the difference between these categories

@roshanshariff asked about this recently too.

I will say part of the reason is to do with the bibtex-completion dependency, and the fact that the "insert" commands work differently than does `org-cite-insert` as it works with the `org-cite-make-insert-processor` function.

In org-cite, it makes sense to include `org-cite-insert` at point, because that command behaves differently depending on context. So if point is after an existing key, for example, it appends a new one. If it's on a key, it replaces. If on the "cite" part, it prompts to edit a style.

But the bibtex-completion latex and markdown insert aren't that smart, so they don't make sense to use at point, and can cause unexpected results.

But ...

If we revised those insert citation functions to behave consistently with `org-cite-insert` (something @aikrahguzar already started to do with his latex adapter), then not only could we align the keymaps, but it _might_ also make sense to remove `citar-insert-keys`.

Only practical impediment is my current lack of understanding of buffer/point coding.

**Comment by roshanshariff** [comment]
> [@bdarcus here](https://github.com/bdarcus/citar/pull/390#issuecomment-965118522) I think the direction this is headed is two embark maps, or possibly even one.

I like the idea of having only one target type, but thinking about it more perhaps there are logically two kinds of targets: citations and references.

Citations (subsuming 'oc-citation) are targets found in buffers. Their actions should probably include: open-all-[files/url/notes/bibentries], insert/edit/delete keys, change citation type, and edit pre/suffix.

References (subsuming 'bib-reference and 'citation-key) are targets appearing either in the document as components of citations, or as completion candidates. Their actions should be open [file/url/note/bibentry] and insert (into citation at point or make new citation otherwise)

The target finder should try to find both in documents, but in formats (text/Markdown) that don't support complex citations, perhaps it only returns "reference" targets? In org/latex, it should return both reference and citation targets, as it does in org-mode now with 'oc-citation and 'citation-key. So if you want to operate on one reference, you can just do it, but then you can use embark-cycle to select the full citation and operate on that instead.

Does that make sense?

**Comment by bdarcus** [comment]
> Does that make sense?

Yes, that's basically been the thinking behind the status quo.

But I split a separate two for org because of the `org-cite-insert`/`citar-insert-citation` issue.

**Comment by roshanshariff** [comment]
Complicated because it needs to do the right thing per major mode? And you mentioned that you were having trouble getting it to call 'org-cite-insert` in Org mode, and in plain text modes it needs some point-manipulation to insert at the right place. I can help with getting these working; that will let us get rid of the Org-specific targets, right?

**Comment by bdarcus** [comment]
> Complicated because it needs to do the right thing per major mode? 

Correct: #383.

> And you mentioned that you were having trouble getting it to call 'org-cite-insert` in Org mode, and in plain text modes it needs some point-manipulation to insert at the right place. I can help with getting these working; that will let us get rid of the Org-specific targets, right?

By which you mean the keymaps?

Yes, that's the idea.

**Comment by roshanshariff** [comment]
After working on implementing the context-aware actions, now I'm leaning towards having only one target type (maybe `'citar-reference`?) and therefore only one keymap. As is the case now, the target string can either be a single key or "key1 & key2 & key3" for multi-key citations. We will have two target finders in all modes, similar to what now happens in org-mode: one will return the single key at point, and the other all the keys in the current citation (for modes that support multi-key citations, mostly implemented in #394). So if you're on a particular key, you first get the single key as a target, then the entire citation. If you're on a citation affix but outside any key, you only get the second target type.

Looking at the current set of operations, it seems they should mostly work in all contexts:

| Action | Minibuffer | Buffer Key | Buffer Citation |
| --- | --- | --- | --- |
| open file/url/note/entry | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| insert citation at point (context-sensitive) | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| edit thing at point (style/key) | :x: | :heavy_check_mark: | :heavy_check_mark: |
| insert bibtex entry/formatted reference/keys | :heavy_check_mark: | :x: | :x: |
| refresh library | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |

* open file/url/note/entry
Currently some of these aren't great at dealing with multi-keys (e.g. open entry, #363) but we can probably figure something out. I'm working on a way to unify all the open functions that should also solve this problem (will open a PR soon).
* edit thing at point
Currently in org-mode this just calls org-cite-insert. If point is not on an existing citation, it will prompt for multiple keys and insert a citation at point (exactly like edit/insert citation at point does). We can adopt the same behaviour for all major modes, making it behave like insert-citation when called from the minibuffer.
* insert bibtex/formatted reference/keys
These are clearly unwanted if you invoke them when point is inside a citation, but the results are very predictable and not confusing (getting a blob of text at point). Most users will probably undo and carry on.
* refresh library
This should probably be marked as a repeatable action in Embark, so you can invoke it and then go on to invoke one of other actions (and it should print a message to the echo area so users know it did something).

Any thoughts?

**Comment by bdarcus** [comment]
> Any thoughts?

Not anything specific ATM.

But in general, I think priority should be on the UX.

If simpler (in this context, one embark map) is consistent with a better, more elegant and clear, UX, then that should be the approach.

If OTOH, two is better, then that should be the approach.

If unsure, perhaps start by simplifying to 2, and then can iterate based on feedback?

For org, I do want to be able to edit a citation style and affixes at point, but ATM I don't have a strong opinion on whether or not I have to be able to do with `embark-act`. I'm just not sure.

**Comment by roshanshariff** [comment]
I agree with the priority being on the UX. In fact, the reason I proposed this change is that it's confusing to have a mostly-identical but slightly different Embark keymap available depending on whether the current target is a single key or multi-key citation. And from the table above, it seems like all the operations have sensible meanings in all contexts.

For org-mode the "edit-thing-at-point" operation in the table is effectively a pass-through to org-cite-insert. It ignores the target and just does something sensible based on the location of point; that's why I thought it should be available in all contexts. In particular, if you invoke it with point on the style part, it'll offer to change it; or if point is on a particular key it will change that. I don't believe it has any support for editing affixes; it just inserts a new key at the beginning/end of the citation if you're on the prefix/suffix.

My proposal is to continue to have this command be a wrapper around org-cite-insert, but also implement equivalent functionality for other major modes.

**Comment by bdarcus** [comment]
Just a thought as I'm taking a break ...

It could be that we only have an embark target finder for citation-references?

And maybe add `citar-edit-citation` to the direct keymap; something like `C-e`?

That might simplify things at-point.

But still might be value to have two keymaps, with at-point more focused on "open" actions.

**Comment by bdarcus** [comment]
On this:

> I'm working on a way to unify all the open functions that should also solve this problem (will open a PR soon).

Up to you, but you might open an issue first to discuss the plan?

I've thought about this issue, but never came to a conclusion about the obvious path forward; each that I considered had trade-offs.

**Comment by roshanshariff** [comment]
> I've thought about this issue, but never came to a conclusion about the obvious path forward; each that I considered had trade-offs.
Yeah, I was also experimenting with different approaches to see if there was a reasonable alternative. I have some ideas but I'm not sure if they're going to be implementable, so I figured I would write some code first just to make sure. I'll open an issue with a potential plan if the experiment is successful.

**Comment by minad** [comment]
@roshanshariff 

> After working on implementing the context-aware actions, now I'm leaning towards having only one target type (maybe 'citar-reference?) and therefore only one keymap.

This is what I would advocate. I would sacrifice a bit superficial UI for a tighter and easier to understand internal representation (single key, single keymap). I also consider the internal construction at least to some extent as part of the interface, which becomes true as soon as the user starts to interact with a package on the elisp level. For example a user may want to add custom actions - then it is easier to adjust only a single keymap. This it is all a matter of preference.

**Comment by roshanshariff** [comment]
For now, in #394, we've brought it down to two target types (removing the org-specific one). But I think we should keep this issue open and reconsider later about combining the two remaining ones (minibuffer and at-point).

**Comment by bdarcus** [comment]
I'd like to close this. Most of the thread ended up being about the keymaps, but I was wondering about the categories?

Keep as is, or change to citar-specific?
