### ISSUE TITLE
Rename citar-file-note-org-include defcustom

### ISSUE THREAD

**Issue by bdarcus** [bdarcus/citar#432]
This defcustom is currently in `citar-org`, so should be called `citar-org-note-include`.

Or it should become a more general defcustom, in either `citar-file` or `citar`.

Possibly related to #431.

Thoughts?

cc @localauthor @roshanshariff

**Comment by localauthor** [comment]
Seems that it makes sense to rename it and keep it in `citar-org`, since there isn't a more general function to open notes with than `citar-org-open-notes-default`.

Not sure if you've considered offering a more general (not org specific) default notes function, or what such a thing would look like (`citar-open-notes-default`?), but that might call for a more general `citar-note-include`.

**Comment by bdarcus** [comment]
> Not sure if you've considered offering a more general (not org specific) default notes function, or what such a thing would look like (`citar-open-notes-default`?), but that might call for a more general `citar-note-include`.

Indeed, that's the broader question behind the question. The obvious use case is someone wanting, say, to have markdown notes, using let's say pandoc (which has YAML headers).

**Comment by roshanshariff** [comment]
Maybe the pre-formatting of new notes could be a separate step from opening notes? My initial thought is that there should be a `citar-open-notes-default` that just opens a note using `find-file`, and if the file doesn't already exist it then calls the functions in `citar-new-note-functions` with the bib entry as argument. Those functions can do things like adding an org ID (if the new buffer is in org-mode), adding the initial template, etc.

**Comment by bdarcus** [comment]
> Maybe the pre-formatting of new notes could be a separate step from opening notes?

Yes of course; that makes more sense.

> ... and if the file doesn't already exist it then calls the functions in citar-new-note-functions with the bib entry as argument. Those functions can do things like adding an org ID (if the new buffer is in org-mode), adding the initial template, etc.

I'm a bit fuzzy on how this would work.

Would each function insert some piece of text?

I suppose another direction is to just make the templating more powerful/flexible.

**Comment by roshanshariff** [comment]
> I'm a bit fuzzy on how this would work.

Yeah, I'll need to think more about the details.

> Would each function insert some piece of text?

In principle, yes; each function could insert text or otherwise modify the buffer (or do anything else that's needed: for example, adding the note's filename to the "file" entry in the bibtex). The advantage to making them functions is they can put the new text in the appropriate place and leave point where needed. So the org-id function or the YAML front-matter function can add text to the beginning of the buffer but leave point where it is. And the template-inserting function would just insert at point, so it would be useful regardless of whether the note is using Org or Markdown.

> I suppose another direction is to just make the templating more powerful/flexible.

This could a be a good use for `skeleton-insert` and friends, since they already implement a very powerful interactive templating system. I'll have to look into how to make bibtex entry fields available inside the skeleton in a convenient way.

**Comment by bdarcus** [comment]
Hmm ... I guess in principle this could be refactored as that list of functions.

```elisp
 (setq citar-org-note-include '(org-id org-roam-ref)
```

In any case, I don't think there's any rush on this. I think we just want to nail it down before 1.0/stable.

**Comment by tshu-w** [comment]
@bdarcus Hi, I find `citar-file-note-org-include` is not used in `citar-org-roam-make-preamble` and it will always create id and refs

**Comment by bdarcus** [comment]
> Indeed, that's the broader question behind the question. The obvious use case is someone wanting, say, to have markdown notes, using let's say pandoc (which has YAML headers).

I just noticed, @localauthor, that you use markdown in zk?

There's a practical example that would support this.

**Comment by localauthor** [comment]
What's the standing issue here? I've lost the thread, since a lot has changed since the issue was posted. 

If it's about injecting info from citar into markdown notes then the `zk` case may not be helpful, because all the insertion is done by `zk`, and even that doesn't follow standard markdown formatting 😬. In any case, I set `citar-open-note-function` to the following:

https://github.com/localauthor/.emacs.d/blob/efb0446b83506500bd5004eb028ff91f17604ccf/init.el#L1519-L1538

```elisp
  (defun gr/citar-zk-open-note (key entry)
    "Custom function for citar-open-note-function."
    (let* ((filematch (format "\\`[0-9]\\{12\\}.%s.*\\.\\(?:md\\)\\'"
                              (regexp-quote key)))
           (results-key (seq-mapcat
                         (lambda (dir)
                           (if-let ((file (directory-files dir t filematch)))
                               file))
                         citar-notes-paths)))
      (if results-key
          (funcall 'find-file (car results-key))
        (if (y-or-n-p "No note associated - create one?")
            (let* ((template (citar-get-template 'note))
                   (title
                    (when template
                      (subst-char-in-string ?: ?-
                                            (citar--format-entry-no-widths
                                             entry
                                             template)))))
              (zk-new-note title))))))
```

**Comment by bdarcus** [comment]
> What's the standing issue here? I've lost the thread, since a lot has changed since the issue was posted.

For the narrow issue of the name, I guess I can close this, since I removed that defcustom.

But this has raised the question for me if there needed more general changes for possible other major modes.

I'll close this then. If we think yes, can open another issue.

> ... and even that doesn't follow standard markdown formatting

I was surprised you weren't using pandoc with it's yaml headers.
