### ISSUE TITLE
Cannot access an alternate action via embark-act

### ISSUE THREAD

**Issue by tshu-w** [bdarcus/citar#435]
**Describe the bug**
I cannot access an alternate action via embark-act and got 
```
Debugger entered--Lisp error: (wrong-type-argument listp 75)
  car(75)
  mapcar(car "Key not found")
  #f(compiled-function #'sequence #<bytecode 0x1848f6064b415174>)(car "Key not found")
  apply(#f(compiled-function #'sequence #<bytecode 0x1848f6064b415174>) car "Key not found" nil)
  seq-map(car "Key not found")
  citar--extract-keys("Key not found")
  citar-open-entry("Key not found")
  funcall-interactively(citar-open-entry "Key not found")
  command-execute(citar-open-entry)
  #f(compiled-function () #<bytecode 0x138ee03c82a33779>)()
  apply(#f(compiled-function () #<bytecode 0x138ee03c82a33779>) nil)
  #f(compiled-function () #<bytecode 0x279e31c6c0e81bc>)()
  #f(compiled-function () #<bytecode 0x40d16cff2c139ee>)()
```

**To Reproduce**
1. `M-x citar-open`
2. select some entries
3. `C-.` to run `embark-action`
4. Select other action like `citar-open-entry`

**Expected behavior**
embark action run correctly.

**Emacs version:**
GNU Emacs 29.0.50 (build 1, x86_64-apple-darwin21.1.0, NS appkit-2113.00 Version 12.0.1 (Build 21A559)) of 2021-11-01

**Additional context**
my citar config:
```emacs-lisp
(use-package citar
  :straight t
  :init
  (setq org-cite-insert-processor 'citar
        org-cite-follow-processor 'citar
        org-cite-activate-processor 'citar)
  :config
  (setq citar-at-point-function 'embark-act
        citar-bibliography (mapcar (lambda (file) (concat bibtex-file-path file)) bibtex-files)
        citar-library-paths `(,(concat bibtex-file-path "files/"))
        citar-notes-paths `(,bibtex-notes-path))
  :general
  (tyrant-def "aC" 'citar-open))
```

**Comment by localauthor** [comment]
With any function that uses `completing-read-multiple`, like `citar-open`, it is expected that your selections will be passed to the original function --- `citar-open` in your case.

When you invoke `embark-act` after making selections, the selections are not passed to embark, since embark works on whatever is currently at point.

If you are invoking `embark-act` at the top of the minibuffer, where there is no text, you are essentially passing 'nil' to whatever embark action you choose. Hence "Key not found."

If you move your point down to one of the selections and invoke `embark-act`, you should be able to run an action on that selection --- but not on all the selections.

As for addressing this issue, making it clear to the end-user what is expected or what has gone wrong, I'm not really sure at the moment.

**Comment by tshu-w** [comment]
> If you move your point down to one of the selections and invoke `embark-act`, you should be able to run an action on that selection --- but not on all the selections.

I have also tried this but failed.

**Comment by localauthor** [comment]
One thought:

What you're trying to do would seem to be a good candidate for the `embark-become` functionality, which allows you to reroute the current input to another function (in your case, from `citar-open` to `citar-open-entry`), except that `embark-become` seem to work only on minibuffer input, not on on `completing-read-multiple` selections.

But that would be a pretty long way around anyway (not to mention needing to ask that CRM functionality be added to `embark-become`...).

It seems, currently, that if you want to act on multiple selections, you'll have to invoke the desired function in the first place.

**Comment by localauthor** [comment]
> > If you move your point down to one of the selections and invoke `embark-act`, you should be able to run an action on that selection --- but not on all the selections.
> 
> I have also tried this but failed.

Hmm, I don't know then. It works on my end. Maybe someone else can reproduce this?

**Comment by bdarcus** [comment]
> I have also tried this but failed.

Does it fail on all actions?

**Comment by tshu-w** [comment]
> > I have also tried this but failed.
> 
> Does it fail on all actions?

Yes, all actions cannot get what I select. To be conformed, doesn't I point the second entries right?
<img width="1313" alt="Screen Shot 2021-11-23 at 20 33 12" src="https://user-images.githubusercontent.com/13161779/143024643-8535d2d6-04f3-4961-aedd-9c2da48da282.png">

**Comment by bdarcus** [comment]
Weird. This is what I see (on Doom):

![image](https://user-images.githubusercontent.com/1134/143026062-abbcd7f6-b1c6-421a-b771-2d6be82325bb.png)

**Comment by tshu-w** [comment]
<img width="1057" alt="Screen Shot 2021-11-23 at 20 55 34" src="https://user-images.githubusercontent.com/13161779/143027763-8fa4b817-0645-4211-a9b6-9d01e175db6f.png">
Yes, I don't know why I cannot get candidate selected on my side, I will check if something conflict when I have time. Sorry for interrupt.

**Comment by roshanshariff** [comment]
I was able to partially reproduce this and I think there are two things happening:

First, when you `embark-act` in the minibuffer without any candidate selected, it is actually acting on whatever you've typed into the completion prompt. If you haven't typed anything, this is the empty string. This is especially likely to happen with `consult-completing-read-multiple`, because it moves the point back to the input line immediately after you select a candidate.

That should be fine, however, since empty minibuffer input should just result in `citar-select-refs` returning the empty list, so `citar-open-entry` should say there are no associated resources. But there is a small bug in `citar-select-refs` that causes it to return the string "Key not found" when given empty minibuffer input. That's what caused the error you see. I'll include a fix in a forthcoming PR.

**Comment by bdarcus** [comment]
I merged this @tshu-w. Let us know?

**Comment by tshu-w** [comment]
Thx @roshanshariff, It works fine as I excepted now.
