### ISSUE TITLE
Review public/internal function names, docstrings

### ISSUE THREAD

**Issue by bdarcus** [bdarcus/citar#438]
There's maybe some inconsistency ATM that would be nice to resolve as we approach 1.0/stable.

See, for example:

![image](https://user-images.githubusercontent.com/1134/143724141-498c8af8-f749-4852-9a8a-7032d727719a.png)

My hope is that release can provide a stable foundation for future growth and iteration.

**Comment by salutis** [comment]
I think the following two variables should have the same prefix:

```emacs-lisp
(setq-default citar-library-paths (list my/bibtex-directory)
              citar-file-extensions '("pdf"
                                      "html"
                                      "epub"
                                      "txt"
                                      "png"
                                      "jpg"))
```

Perhaps rename `citar-file-extensions` to `citar-library-file-extensions`? 

The same applies to all the other APIs that say "file" and nothing else. We should always say "bibliography-file" or "library-file" because "file" can mean either.

Other ideas:

- `citar-bibliography` could become `citar-bibliography-files` to match others
- `citar-org-local-bib-files` needs a better name (Org file, Org document, or Org buffer instead of "Org-local"; also "bib" vs "bibliography" elsewhere)

**Comment by salutis** [comment]
I also find `citar-open-entry` vs `citar-open` slightly unclear because `citar-open` also opens some "entry".

**Comment by bdarcus** [comment]
> I also find `citar-open-entry` vs `citar-open` slightly unclear because `citar-open` also opens some "entry".

I agree, but haven't thought of a better name that's also concise. There's other discussions here about these name issues.

**Comment by localauthor** [comment]
The [official guidance](https://www.gnu.org/software/emacs/manual/html_node/elisp/Coding-Conventions.html) on private functions is pretty brief: "Use two hyphens to separate prefix and name if the symbol is not meant to be used by other packages."

### Internal functions (should probably have double hypen):
- citar.el
  - citar-get-value
  - citar-has-a-value
  - citar-display-value
  - citar-has-file
  - citar-has-note
  - citar-get-template
  - citar-get-link
  - citar-open-multi
  - citar-select-group-related-resources

- citar-file.el
  - citar-file-parser-default
  - citar-file-parser-triplet

- citar-org.el
  - citar-org-id-get-create

- citar-latex.el
  - citar-latex-select-command
  - citar-latex-is-a-cite-command

### Not sure about these:
- from citar.el; any thoughts one way or the other?
  - citar-select-ref
  - citar-select-refs
  - citar-select-resource

- from citar-file.el; any reason to make this public? 
  - citar-file--directory-files

**Comment by bdarcus** [comment]
Yes, two hyphens.

But the way I think about it is it's public we're encouraging people to use it's and saying they can rely on it.

If you have a chance, can you weigh in on this @roshanshariff?

**Comment by roshanshariff** [comment]
I agree with @bdarcus that functions that have a reasonable stable and well-defined interface should be made public, even if we don't think of them as user-facing; this criterion is a little vague though. So maybe we can consider the main functionality that should be exported:
* Information from the bibliography entry: Maybe `citar--get-entry`, `citar-get-value`, `citar-has-a-value`, `citar-display-value`?
* Notes: `citar-has-notes` and `citar-file--get-note-filename`?
* Files: High-level functions like `citar-file--files-for-multiple-entries` and `citar-has-file`, but not lower level functions that scan directories or parse file fields, because we want third-party code to treat all these kinds of files the same.
* Links: `citar-get-link` probably.

Otherwise, I mostly agree with @localauthor's suggestions. It's probably good to err on the side of making things private for now.

**Comment by bdarcus** [comment]
> * Maybe `citar--get-entry`, `citar-get-value`, `citar-has-a-value`, `citar-display-value`

Why the first private?

**Comment by roshanshariff** [comment]
Sorry, I meant to say that it's currently private, but should perhaps be public.

**Comment by bdarcus** [comment]
> Sorry, I meant to say that it's currently private, but should perhaps be public.

OK, so you're suggesting all of the functions you explicitly list be public then?

**Comment by roshanshariff** [comment]
Yes, to provide the main functionality I thought might be needed to extend Citar.

**Comment by minad** [comment]
I would keep as much private as possible. It is easier to open up APIs than to remove them later on. Since citar is not a library but a user facing package there is nothing wrong if most things are kept private and only expose functionality on a case by case basis if requested. The question is to which extent citar functions can be considered library functions, which are useful for other packages or user configurations.

**Comment by bdarcus** [comment]
@localauthor - any input on this?

I'm thinking this is likely the only issue that needs resolving before a possible 1.0 tag.

I haven't paid much attention to version numbers, but they do matter for distributions. For example, GUIX has a citar package, which gets updated when I tag a new version.

**Comment by localauthor** [comment]
I'm persuaded by the distinction minad highlights between library and user-facing package,  to the end that I think I'll stick by my original list above and suggest that the 'get' and 'has' functions be private.

I would also suggest that `citar-select-resource` be private, while `citar-select-ref(s)` remain public.

Otherwise, this seems like a low final barrier to 1.0, so not a lot of reason to linger on it, I think.

**Comment by bdarcus** [comment]
Oh, sorry; I missed your post above!

**Comment by aikrahguzar** [comment]
Looks good to me. I don't have strong feelings about public/private apis except that interactive commands should be public.

**Comment by bdarcus** [comment]
I started implementing this, and recording some additional questions or issues, on the linked PR.
