### ISSUE TITLE
Add ex/citar-search-pdf-contents to wiki

### ISSUE THREAD

**Issue by bdarcus** [bdarcus/citar#477]
I don't think we necessarily want to add this to citar per se (it's another dependency, and specific to PDF), but this could be a good candidate for the wiki.

----------------------

Adding this in case others are interested; an idea from a private email.

Is there some way to elegantly:

- search within some subset of (pdf) files (by, for example, author)
- browse through the results, perhaps narrow them, and then to open the selected result's pdf at its respective page number

It seems to me a solution that hooks up citar and pdf-tools would be the way to go, and specifically to exploit [pdf-occur](https://github.com/politza/pdf-tools/blob/c510442ab89c8a9e9881230eeb364f4663f59e76/lisp/pdf-occur.el).

![image](https://user-images.githubusercontent.com/1134/145401178-0e3700a9-b060-47b0-94aa-68994c30bdcd.png)

It seems like `pdf-occur-dired-do-search` should be what we need. To use it, use `dired` to mark the files you want to search, and then run that command.

Just need to figure out which files to mark (using citar), and how much of this can be handled programmatically.

_Originally posted by @bdarcus in https://github.com/bdarcus/citar/discussions/476_

Turns out the solution is `pdf-occur-search`.

```elisp
(defun ex/citar-search-pdf-contents ()
  ;; from localauthor
  "Search pdfs."
  (interactive)
  (let* ((refs (citar-select-refs))         
         (files (citar-file--files-for-multiple-entries refs citar-library-paths '("pdf")))
         (string (read-string "Search string: ")))
    (pdf-occur-search files string t)))
```

**Comment by roshanshariff** [comment]
If I understand correctly, the key step is to get a dired buffer showing all the files for selected entries?

Another way to accomplish this is to run `citar-open-library-files`, select the entries you want, then when offered the choice of files, run `embark-export` (which is available through `embark-act`). This creates a dired buffer with all the associated files, including those listed in the `file` field of the entry.

At that point you have to mark all the PDFs and you can run `pdf-occur-dired-do-search`. This last step is a little clunky, but it could be easier of `pdf-occur-dired-minor-mode` had a command to mark all PDFs (or search all PDFs without marking them).

**Comment by roshanshariff** [comment]
The procedure I gave does this this, using `citar-open-library-files` and `embark-export`. Do you mean a way to do it without Embark?

The code to look at is in `embark-export-dired`, and it basically comes down to calling `dired` with `(DIR . FILES)`, where `DIR` is the directory ("/" works for this) and `FILES` is a list of files, which you can get from `citar-file--files-for-multiple-entries`.

The advantage of doing it this way is that it includes files given in the "file" field, rather than just files in a particular directory.

**Comment by bdarcus** [comment]
I mean using dired directly.

I'm not sure that's the best approach, but I wanted to experiment with it.

**Comment by bdarcus** [comment]
Hmm ... I'll experiment more, but the exported buffer doesn't include all the files; it includes the candidates against which one can run the `citar-open-library` command. I'm not seeing how to then search the contents of the list of PDFs associated with them.

**Comment by bdarcus** [comment]
Oh wait;  I missed a step; hang on.

**Comment by localauthor** [comment]
Does this do what you're looking for?

```
(defun ex/citar-search-pdf-contents ()
  "Search pdfs."
  (interactive)
  (let* ((refs (citar-select-refs))
         (dir
          (if (equal (length citar-library-paths) 1)
              (car citar-library-paths)
            (completing-read "Directory to search: " citar-library-paths)))
         (files (citar-file--files-for-multiple-entries refs (list dir) '("pdf")))
         (string (read-string "String: ")))
    (pdf-occur-search files string t)))
```

**Comment by localauthor** [comment]
What's the problem with running this on all the directories listed in `citar-library-paths`? Like this:

```
(defun ex/citar-search-pdf-contents ()
  "Search pdfs."
  (interactive)
  (let* ((refs (citar-select-refs))         
         (files (citar-file--files-for-multiple-entries refs citar-library-paths '("pdf")))
         (string (read-string "String: ")))
    (pdf-occur-search files string t)))
```

**Comment by localauthor** [comment]
I've been holding out on using emacs for PDFs, but this function might be a tipping point. Great idea.

**Comment by bdarcus** [comment]
I added this to the wiki for now. I'm thinking we can use this to develop ideas for new functions.

https://github.com/bdarcus/citar/wiki/Example-functions#pdf-tools-integration

**Comment by roshanshariff** [comment]
I've also wanted to run actions on all filtered candidates, but I'm not sure where this functionality should be added. Perhaps `consult-completing-read-multiple` could have a "select all" command? Embark has `embark-minibuffer-candidates` and `embark-vertico-candidates` to collect the candidates, but as you can see this is somewhat specific to the completion system.

**Comment by bdarcus** [comment]
> I've also wanted to run actions on all filtered candidates, but I'm not sure where this functionality should be added. Perhaps `consult-completing-read-multiple` could have a "select all" command? Embark has `embark-minibuffer-candidates` and `embark-vertico-candidates` to collect the candidates, but as you can see this is somewhat specific to the completion system.

I think @minad and @oantolin had concluded it probably belongs in embark fro this reason. See:

https://github.com/oantolin/embark/issues/253

... and in particular https://github.com/oantolin/embark/issues/253#issuecomment-885203387.

**Comment by minad** [comment]
> I think @minad and @oantolin had concluded it probably belongs in embark fro this reason. See:

Yes, but it's not yet entirely clear how the exact solution for multi actions could look like. A rough plan:

1. `embark-act-all`: A command which acts on all candidates in the current context retrieved from `embark-candidate-collectors`.
2. Refine some candidate collectors to support marking. Some collectors like dired already do. For dired if files are marked only the marked files are returned, otherwise all files are returned.
3. In the context of Vertico add a `vertico-mark` command and modify the `embark--vertico-candidates` collector to respect marking. Unfortunately this step is entirely UI dependent. (I've considered another alternative where an `embark-select/collect-single` command is added to Embark only. This command takes the current target/candidate and adds it to the last Embark collect buffer. After collecting all the candidates the user can run `embark-act-all` in the collect buffer. But this approach does not sound user friendly.)

Step 2 and 3 are optional, the only moderate addition needed to act on all candidates is `embark-act-all`. However without 3 I suspect that acting on multiple candidates is not convenient since then the user has to ensure that only relevant candidates remain after filtering.

**Comment by bdarcus** [comment]
> Step 2 and 3 are optional, the only moderate addition needed to act on all candidates is `embark-act-all`. However without 3 I suspect that acting on multiple candidates is not convenient since then the user has to ensure that only relevant candidates remain after filtering.

True, but 1 might be a reasonable first step?

At least for this use case (user wants to search the content of PDFs of associated with the selected candidates), it would be.

**Comment by minad** [comment]
> True, but 1 might be a reasonable first step?

Sure, but it is up to @oantolin if he would accept such a PR. Adding such a command should be a small addition. Maybe a bit of refactoring of `embark-act` is needed such that the acting logic can be reused for single and multiple candidates. In any case `embark-act-all` should probably as the user for confirmation to avoid bad surprises.

If I recall correctly we also discussed another possible solution for multiple candidates, where target finders are modified such that they don't return a single candidate but a list of multiple candidates. I am not sure if that would be better. It seems better to me to reuse the `embark-candidate-collectors` for the act multi functionality.

**Comment by oantolin** [comment]
Reusing `embark-candidate-collectors` for an `embark-act-all` sounds good to me. And, as @minad says, it's a relatively small addition that may require refactoring `embark-act` a bit.

**Comment by oantolin** [comment]
I wrote en `embark-act-all` command, see oantolin/embark@91e6db4dc029cc87ff3315f88552468de7344e30 and bound it to `A` in the general map (of course, you can also bind outside the embark keymaps if you wish). Please test!

**Comment by roshanshariff** [comment]
> Am I right we should add something like this first function?

`citar-file--files-for-multiple-entries` already includes files from both sources, the file field and the library directories. So the function that @localauthor wrote [above](https://github.com/bdarcus/citar/issues/477#issuecomment-990308448) should already do the right thing.

**Comment by roshanshariff** [comment]
@oantolin, do you think it makes sense to be able to mark a command to run once with all the candidates, rather than repeatedly for each candidate? That would be useful here, for running a search over the PDF files of all entries.

Of course, Embark would need to know how to coalesce all the candidates into one minibuffer input, maybe assuming the command uses `completing-read-multiple`?

**Comment by minad** [comment]
@roshanshariff Yes, I believe this is something we also considered at some point in the old discussion. For crm commands `embark-act-all` should join the candidate and pass them at once. This should fit cleanly into the current picture. However it may be a bit problematic to auto detect crm in practice. Furthermore there is the problem that crm string joining is not well defined since we don't know the crm separator. So maybe we need an `embark-crm-action` variable?

For my taste the current `embark-act` and `embark-act-all` code is a bit messy for my taste (no offense @oantolin :-P) and it will get worse if we add the crm target injection code path. So I guess we should massage all this a little bit. See also https://github.com/oantolin/embark/pull/419, there are still a few minor issues with the current `embark-act-all`.

**Comment by minad** [comment]
This reminds me of another point - do we also need a CRM candidate collector which only collects the selected candidates instead of all candidates? At this point the design clashes a bit with a potential `vertico-mark` command, see https://github.com/bdarcus/citar/issues/477#issuecomment-990358698. `vertico-mark` would be usuable in the context of non-crm commands, but it wouldn't make so much sense in the crm context. 

Maybe at this point I should deprecate and remove `consult-completing-read-multiple` and replace it with a proper vertico-crm implementation. In the context of vertico-crm, vertico-mark would play a dual role as candidate selector for crm and as candidate subset selector for the embark candidate collector. In the context of non-crm vertico-mark would only be relevant for the candidate collector. This approach could lead to a uniform crm and completing-read UI.

**Comment by roshanshariff** [comment]
@minad, I for one really like the idea of a vertico CRM implementation :+1:

The `vertico-mark` approach opens the door to some really nice UI improvements that seem beyond the reach of `consult-crm`. Since many Citar commands use CRM, their workflows would be quite elegant. And, of course, you could easily address the issue we have here by having a "mark all candidates" command.

**Comment by oantolin** [comment]
@minad said:

> For my taste the current `embark-act` and `embark-act-all` code is a bit messy (no offense @oantolin :-P)

None taken! It's messy for my taste too. In the case of `embark-act-all` it's because I wanted to get a decent prototype out the door in the time I had yesterday and would clean up later. In the case of `embark-act`, I don't really have an excuse. 😛 

@roshanshariff Yes, we should definitely think of adding a way to pass all targets at once to an action. One issue is that `crm-separator` is not something you can use to join candidates but a regexp that *recognizes* such strings. I guess a simple table mapping common values for `crm-separator` to a string you can use for joining might be good enough. I believe that's what Selectrum uses for example.

Also, I was thinking that maybe the `vertico-mark` functionality can be added in a completion UI independent way with the old embark-select idea. That idea was to have a command to add a single target to a special Embark collect buffer, and then from that buffer one could run an action on all candidates. To me the only thing that sounds awkward about that is switching to the special collect buffer to run `embark-act-all` and then probably killing the buffer. This could be remedied by making the buffer ephemeral (= killed automatically when when you quit the minibuffer) like the Embark collect completions buffer, and adding a candidate collector with higher priority that, if the special collect buffer exists, returns those candidates.

**Comment by minad** [comment]
@oantolin yes, this is the embark-select idea I had in mind and we discussed earlier. It does not sound that bad in the way you describe it 😄

 I suspect that the UI would be slightly worse than a specifically tailored vertico UI. But with the big advantage of being completion UI independent. And the other big advantage that I don't have to change anything in vertico 😛

**Comment by minad** [comment]
I think we should at least give the UI agnostic approach in embark a try as a prototype. If it turns out that it is not user friendly enough we can still opt for UI specific solutions. 

In the case if embark a UI specific solution could rely on marking the candidates directly in the collect buffer. You've mentioned some addition to the tabulated list mode a while ago. Maybe this already works? Does it also work in grid mode?

**Comment by bdarcus** [comment]
> I wrote an embark-act-all command ...

Thanks @oantolin! I tested it a bit, and seems to work as expected.

> For crm commands `embark-act-all` should join the candidate and pass them at once. This should fit cleanly into the current picture.

This indeed was my wonder in terms of next steps.

The obvious cases here where it's important to do this is:

1. this one; searching many PDFs
2. `citar-copy-reference`, which adds formatted bibliographic entries to the kill ring; obviously if I do this with 10 of them and `yank`, I get only one reference (plus we could sort them with a list)

> Maybe I should deprecate and remove consult-completing-read-multiple and replace it with a proper vertico-crm implementation. In the context of vertico-crm, vertico-mark would play a dual role as candidate selector for crm and as candidate subset selector for the embark candidate collector. In the context of non-crm vertico-mark would only be relevant for the candidate collector. This approach could lead to a uniform crm and completing-read UI.

How might such a mark UI work vis-a-vis standard selection?

I wonder if, from a user POV, the only difference is with the latter the prompt is reset upon selection, while in the latter it would stick?

I seem to remember a conversation on the selectrum UI about the idea to allow something like `shift-TAB` to preserve the input. 

Does that have promise?

**Comment by minad** [comment]
@bdarcus 

> How might such a mark UI work vis-a-vis standard selection?

For crm vertico-mark would be the same as standard selection. For normal cr commands vertico-mark would not be relevant for the return value but only for actions. However I think we should first try to implement the embark-only solution since it will integrate automatically with all different frontends. Only if the result is not satisfactory we should consider UI-specific solutions.

Before I made consult-crm I had a vertico-crm prototype. But the prototype was insufficient and didn't work in all scenarios. Therefore I discarded that approach and went with consult-crm. So it is a lot less obvious how the perfect vertico-crm UI looks like if you are really implementing it in Vertico. The consult-crm UI already goes a long way with limited means and the advantage that it can be used with different UIs.

**Comment by bdarcus** [comment]
> I think we should first try to implement the embark-only solution since it will integrate automatically with all different frontends.

Makes sense.

And the idea here is one would mark in a collect buffer? So a workflow something like ...

1. filter candidates
2. `emark-collect-snapshot`
3. mark candidates
4. run command

...?

> A shift-TAB input preserving submit command can be easily implemented for consult-crm in the user config ...

And you please give me an example?

**Comment by minad** [comment]
> Can you please give me an example?

I don't have an example at hand. But the `+vertico` commands of Doom which are used for `consult-completing-read-multiple` can store the `(minibuffer-contents)` and inject the contents again in the next iteration.

**Comment by bdarcus** [comment]
WDYM by "next iteration"?

**Comment by minad** [comment]
consult-crm behaves like multiple calls to completing-read in a loop. After each selection a "new iteration" is started. However technically it works differently internally, so iteration is not really the right word. What I should say, after submitting the selection the original input string should be inserted again.

**Comment by bdarcus** [comment]
I'm going to close this, since it's now on the wiki, and we've done what we can with it.

But think this is a pretty cool little command we may want to include in citar proper at some point.

Separately, I did suggest to iyefrat to include `shift-TAB` in the doom vertico module, and he liked the idea.
