### ISSUE TITLE
Too much bold?

### ISSUE THREAD

**Issue by salutis** [bdarcus/citar#553]
I see almost everything in bold face. Why?

# Citar

<img width="1008" alt="Screen Shot 2022-02-11 at 14 05 48" src="https://user-images.githubusercontent.com/1158274/153596623-6f24631b-bc2b-4fc1-a947-b6b501610e43.png">

# Other UIs

<img width="1005" alt="Screen Shot 2022-02-11 at 14 05 36" src="https://user-images.githubusercontent.com/1158274/153596607-2e8b2c59-5013-46a8-acd5-c3ac2c62391b.png">

**Comment by bdarcus** [comment]
This is not a bug; just the way that face is defined.

Take a look at the faces and adjust them yourself?

**Comment by salutis** [comment]
@bdarcus Thanks, and I will take a look. Do you think this makes for a good default?

**Comment by bdarcus** [comment]
I like it ;-)

But I'm not wedded to it. It's intended to "highlight" the most important content.

**Comment by salutis** [comment]
@bdarcus 

> But I'm not wedded to it. It's intended to "highlight" the most important content.

Ah, I see. I made the window super-wide, and now I see that Citar considers everything except the key and the type "important" or highlighted. How does Citar make that decision?

P.S. I could perhaps talk to Prot of Modus Themes to special-case the `citar-highlight` face to avoid the overuse of bold text in this context. It does look _super-weird_ next to everything else in Emacs; I see bold text here and there, but I have never seen an entire page shown in bold.

**Comment by salutis** [comment]
@bdarcus Thank you for the pointers! I opened an issue with Modus Themes:

 https://gitlab.com/protesilaos/modus-themes/-/issues/280

**Comment by bdarcus** [comment]
To go back to this, if you or @protesilaos have suggestions for a better default face definition, I'm happy for the input.

**Comment by protesilaos** [comment]
Hello @bdarcus!  I will take another look later today and make a suggestion.

**Comment by protesilaos** [comment]
> Two quick things in reply to questions:

Thanks!

> TAB-select a candidate and you will see.

Okay, that is fine.  It might be a bit too much of an emphasis if the
user TAB-selects lots of them at once (say 10), but I assume this is not
normal, right?

> No; that's org-cite. It means it can't find the key.

Very well.  Then it is fine.

**Comment by bdarcus** [comment]
> It might be a bit too much of an emphasis if the user TAB-selects lots of them at once (say 10) ...

I actually don't like the current default; I agree it's too much. Any better suggestion?

>  ... but I assume this is not normal, right?

For some users it may be common to select three of four at a time.

BTW, I just looked: oc-basic applies the "error" face for those; it doesn't define its own.

**Comment by protesilaos** [comment]
> > It might be a bit too much of an emphasis if the user TAB-selects
> > lots of them at once (say 10) ...
> 
> I actually don't like the current default; I agree it's too much. Any
> better suggestion?

Here bold would be more appropriate.  Or bold+italics, if it feels
better to you.  Another decent option is to inherit `success` or, if
you like italics to combine them with it.

> BTW, I just looked: oc-basic applies the "error" face for those; it
> doesn't define its own.

It is a combination of `error` and `org-cite`.  Since it is for a legit
error, it is okay.  I just thought it was always styled that way, which
I found excessive.

> EDIT: as I think about it, in time, it may be sensible to write our
> own fortification function, in which case we'd add a face for
> that. Need to think about that more though.

As you will.  If you need me to test how it looks, I am happy to help.

**Comment by bdarcus** [comment]
> The idea of adding bold to the citar-highlight is interesting as
that is the "important part" of the entry. The problem is with the
gestalt form of all candidates in the minibuffer, where now everything
is emphasised so nothing stands out.

On this, some context.

Originally, the right side of the UI was handled via an affixation function.

But that content can't be searched.

So I went for a similar visual effect, but without the downside.

Whether that was a bad idea or not, am not sure.

**Comment by protesilaos** [comment]
I see.  Making it searchable is better for usability.

> Whether that was a bad idea or not, am not sure.

To take a step back: "too much bold" is not a deal-breaker.  It is, at
most, an exaggeration which does not detract from the package's value
proposition.  Plus, it is implemented with `defface` so the user/theme
can edit the visuals accordingly.

Since you are the maintainer, it is up to you to decide on the defaults.
Themes will always do their own thing.  My belief is that reducing the
overall emphasis improves the interface.  It lets the minibuffer UI
work/look the way it always does, which is consistent with user
expectations.
