### ISSUE TITLE
Error running hook "citar-filenotify-local-watches" after calling `org-edit-special` on a LaTeX fragment

### ISSUE THREAD

**Issue by gkowzan** [bdarcus/citar#567]
**Describe the bug**
Editing a LaTeX fragment in an org mode document with `C-c '` when citar-filenotify-setup is enabled for LaTeX buffers results in the following bug:

    Error (LaTeX-mode-hook): Error running hook "citar-filenotify-local-watches" because: (wrong-type-argument stringp nil)

**Expected behavior**
`citar-filenotify-local-watches` should check if the buffer is backed by a file before trying to monitor for changes

**Emacs version:**
29.0.50 ([deathwish](https://copr.fedorainfracloud.org/coprs/deathwish/)/[emacs-pgtk-nativecomp](https://copr.fedorainfracloud.org/coprs/deathwish/emacs-pgtk-nativecomp/))

**Comment by bdarcus** [comment]
> `citar-filenotify-local-watches` should check if the buffer is backed by a file before trying to monitor for changes

Definitely.

Do you know how to make this change, such that you could submit a PR?

**Comment by gkowzan** [comment]
I can take a stab at it later this week. I took a peek at the source and it shouldn't be to difficult.

**Comment by bdarcus** [comment]
Thanks. I just didn't write that code, and don't use it, so don't know it any better than you do ;-)

**Comment by aikrahguzar** [comment]
This is due to `reftex` throwing an error when the buffer is not backed by a file (this is probably imprecise, likely the error is thrown when reftex can't determine a master file). The is fix is to modify `citar-latex-local-bib-files` so that everything is enclosed in `ignore-errors` i.e.
```elisp
 (defun citar-latex-local-bib-files ()
  "Local bibliographic for latex retrieved using reftex."
  (ignore-errors
    (reftex-access-scan-info t)
    (reftex-get-bibfile-list)))
 ```
I can do the pr but I will need to mess with git a bit so it will take some time. If someone else wants to do it quickly they are welcome.

Somewhat related: Looking at `citar-filenotify-local-watches` it would be nicer to make the hook we add to `kill-buffer-hook` a named function instead of a `lambda`, since `add-hook` behaves better for named functions.

**Comment by bdarcus** [comment]
With #568, I believe this should be fixed. But as I said, I don't use this feature, and don't have a ton of time, so haven't tested it myself (other than to confirm there are no compilation errors or warnings and such).

Let me know @gkowzan?

**Comment by gkowzan** [comment]
Thanks, the fix works for me.
